#!/usr/bin/env bash
# Required: GITHUB_WORKSPACE GUI_BUILD GUI_STAGE OPENMS_INSTALL OPENMS_CONTRIB QT_ROOT_DIR
set -eo pipefail

test -f "$OPENMS_INSTALL/lib/cmake/OpenMS/OpenMSConfig.cmake"
cmake -S "$GITHUB_WORKSPACE" -B "$GUI_BUILD" -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="$GUI_STAGE" \
  -DCMAKE_PREFIX_PATH="$QT_ROOT_DIR/lib/cmake;$QT_ROOT_DIR;$OPENMS_CONTRIB;$OPENMS_INSTALL" \
  -DOPENMS_CONTRIB_LIBS="$OPENMS_CONTRIB" \
  -DOpenMS_DIR="$OPENMS_INSTALL/lib/cmake/OpenMS" \
  -DOPENMS_LEGACY_GUI_WITH_WEBENGINE=OFF \
  -DOPENMS_LEGACY_GUI_BUILD_TESTS=OFF \
  -DOPENMS_LEGACY_GUI_BUILD_THERMO_SMOKE=ON \
  -DOPENMS_LEGACY_GUI_PORTABLE=ON \
  -DOPENMS_LEGACY_GUI_INSTALL_EXAMPLES=ON
cmake --build "$GUI_BUILD" --target GUI openms-legacy-gui-thermo-smoke
cmake --install "$GUI_BUILD" --strip
