#!/usr/bin/env bash
# Required: OPENMS_SOURCE OPENMS_BUILD OPENMS_INSTALL OPENMS_CONTRIB QT_ROOT_DIR
set -eo pipefail

cmake -S "$OPENMS_SOURCE" -B "$OPENMS_BUILD" -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="$OPENMS_INSTALL" \
  -DINSTALL_CMAKE_DIR="$OPENMS_INSTALL/lib/cmake/OpenMS" \
  -DCMAKE_PREFIX_PATH="$QT_ROOT_DIR/lib/cmake;$QT_ROOT_DIR" \
  -DOPENMS_CONTRIB_LIBS="$OPENMS_CONTRIB" \
  -DBUILD_TOPP_TOOLS=ON \
  -DINSTALL_OPENMS_EXAMPLES=OFF \
  -DPYOPENMS=OFF \
  -DWITH_GUI=OFF \
  -DWITH_THERMO_RAW=ON \
  -DWITH_OPENTIMS=ON \
  -DWITH_WNETALIGN=OFF \
  -DWITH_HDF5=OFF \
  -DWITH_ONNX=OFF \
  -DMT_ENABLE_OPENMP=ON \
  -DARROW_USE_STATIC=ON \
  -DENABLE_DOCS=OFF \
  -DENABLE_CLASS_TESTING=OFF \
  -DENABLE_TOPP_TESTING=OFF \
  -DENABLE_PIPELINE_TESTING=OFF \
  -DENABLE_STYLE_TESTING=OFF \
  -DENABLE_THERMO_RAW_TESTS=OFF \
  -DENABLE_UPDATE_CHECK=OFF \
  -DENABLE_CWL_GENERATION=OFF \
  -DGIT_TRACKING=OFF \
  -DHAS_XSERVER=OFF \
  -DPACKAGE_TYPE=none
